# Generated by Django 4.2.2 on 2023-06-20 04:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_rating_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Имя'),
            preserve_default=False,
        ),
    ]
